### ISSUE TITLE
Support Grand Exchange itemdb for oldschool

### ISSUE THREAD

**Issue by stellarhopper** [Raatty/runescapeapi#2]
Hi,

I'm using this to create a Discord bot (Will link to it once released, will be on Github) to query the Grand Exchange itemdb, and was wondering if you had any thoughts about supporting the itemdb for old school.

The only change needed to support this would be in all the GE APIs, in the URLs, replace `itemdb_rs` with `itemdb_oldschool`.

Perhaps the GE APIs can add a parameter that makes this switch?

**Comment by Raatty** [comment]
should hopefully be working now, let me know if there are any more problems
